import zipfile
import uuid
import time
import xml.etree.ElementTree as ET
from xml.dom import minidom

def mid():
    return uuid.uuid4().hex[:20]

def ts():
    return str(int(time.time() * 1000))

def node(title, *children):
    return {"title": title, "children": list(children)}

def leaf(title):
    return {"title": title, "children": []}

# ─── 完整产品结构 ───────────────────────────────────────────

tree = node("洽小秘 产品规划",

  # ══════════════════════════════════════════
  node("客服端",
    node("一期",
      node("登录",
        leaf("激活码登录"),
        leaf("VPN线路选择"),
      ),
      node("工作台",
        leaf("订阅套餐信息"),
        node("AI员工开关",
          leaf("AI销售转化回复"),
          leaf("AI画像标签"),
          leaf("AI总结与分析"),
          leaf("AI辅助回复建议"),
        ),
      ),
      node("会话聊天",
        node("聚合聊天",
          leaf("平台管理"),
          leaf("平台账号管理"),
          leaf("账号搜索"),
          leaf("会话筛选（AI打标）"),
          leaf("消息对话框"),
          leaf("AI员工开关"),
        ),
        node("消息响应",
          node("聚合翻译",
            leaf("AI大模型翻译"),
            leaf("Google翻译"),
          ),
          node("回复",
            leaf("人工回复"),
            leaf("AI回复"),
            leaf("AI辅助回复建议"),
            node("自动回复",
              leaf("关键词"),
              leaf("事件"),
            ),
          ),
        ),
        node("客户资产（基础）",
          leaf("AI会话总结"),
          leaf("AI客户画像"),
          leaf("客户列表"),
          leaf("跟进提醒"),
        ),
      ),
      node("自动化（基础）",
        leaf("关键词回复"),
        leaf("欢迎语回复"),
        leaf("回复内容素材模版"),
      ),
      node("系统设置（基础）",
        leaf("平台设置"),
        leaf("显示设置"),
        leaf("翻译设置"),
        leaf("全局代理"),
        leaf("关于"),
      ),
    ),
    node("二期",
      node("登录（增强）",
        leaf("激活码+账号登录"),
        leaf("忘记密码"),
      ),
      node("客户资产（增强）",
        leaf("行为预测"),
        leaf("互动统计"),
        leaf("粉丝统计"),
      ),
      node("矩阵运营",
        leaf("批量修改账号"),
        leaf("快速建群"),
        node("群发消息",
          leaf("AI智能筛选"),
          leaf("AI生成消息内容"),
        ),
      ),
      node("自动化拓客",
        leaf("自动化加群"),
        node("引流统计",
          leaf("加群转化漏斗"),
        ),
      ),
      leaf("数据统计（完整）"),
      node("安全与数据",
        leaf("环境安全"),
        leaf("数据备份与迁移"),
      ),
      node("系统设置（增强）",
        leaf("快捷键设置"),
        leaf("通用功能设置"),
        leaf("系统设置"),
      ),
    ),
  ),

  # ══════════════════════════════════════════
  node("运营中台",
    node("一期",
      node("登录",
        leaf("账号密码"),
      ),
      node("激活码管理",
        node("新增/编辑",
          leaf("端口/平台"),
          leaf("分组/分配"),
          leaf("工作时间"),
          leaf("自动回复"),
          leaf("多设备登录"),
        ),
        leaf("激活码分组/分配"),
        leaf("激活码分享"),
        leaf("停用"),
      ),
      node("账号列表",
        leaf("工单/线索统计"),
        leaf("查看线索"),
        leaf("登录日志"),
        leaf("移除账号"),
      ),
      node("代理IP管理",
        leaf("导入/导出"),
        leaf("增删查改"),
      ),
      node("AI设置（基础）",
        node("AI角色人设",
          leaf("销售型"),
          leaf("种草型"),
        ),
        node("AI能力",
          leaf("AI销售转化回复（单聊/群聊）"),
          leaf("AI画像标签"),
          leaf("AI售后接待"),
        ),
        node("知识库",
          leaf("商品信息"),
          leaf("店铺信息"),
          leaf("店铺政策"),
        ),
      ),
      node("意图/话术（来自总控+自建）",
        leaf("意图列表（可编辑总控副本）"),
        leaf("话术列表（可编辑总控副本）"),
      ),
      node("分流链接（基础）",
        node("新增/编辑",
          leaf("平台/分流类型/分流模式"),
          leaf("短链/链接域名配置"),
        ),
        leaf("访问记录（基础）"),
      ),
      node("线索管理（基础）",
        leaf("线索列表"),
        leaf("平台工单（创建/编辑/分享）"),
        leaf("线索明细"),
      ),
      node("客户管理（基础）",
        leaf("客户列表"),
        leaf("标签管理"),
        leaf("客户统计"),
      ),
      node("运营管理（基础）",
        leaf("快捷回复"),
        leaf("关键词回复"),
        leaf("欢迎语回复"),
      ),
      node("组织管理",
        leaf("组织架构"),
        leaf("账号角色"),
      ),
      node("日志管理（基础）",
        leaf("登录日志"),
      ),
    ),
    node("二期",
      node("激活码（增强）",
        leaf("线索去重"),
        leaf("客户画像共享"),
        leaf("数据脱敏"),
        leaf("数据权限"),
      ),
      node("设备管理",
        leaf("设备登录日志"),
        leaf("黑名单"),
        leaf("标记企业设备"),
        leaf("清除设备锁"),
      ),
      node("AI设置（增强）",
        node("AI主动营销触达",
          node("用户召回",
            leaf("新客挽回"),
            leaf("沉默用户召回"),
            leaf("老客唤醒"),
            leaf("战败召回"),
          ),
          leaf("营销活动触达"),
          node("内容触达",
            leaf("评论触达"),
            leaf("新粉触达"),
          ),
        ),
        leaf("AI售中消息触达（物流信息）"),
        leaf("AI会话质检"),
      ),
      node("分流链接（增强）",
        leaf("访客数据/客服接访数据"),
        leaf("分配/分组"),
      ),
      node("线索管理（增强）",
        leaf("底粉管理"),
        node("线索分配",
          leaf("规则设置"),
          leaf("提醒设置"),
        ),
        leaf("线索来源同步"),
      ),
      node("客户管理（增强）",
        leaf("客户画像管理"),
        leaf("标签统计"),
        node("客户继承",
          leaf("在职继承"),
          leaf("离职继承"),
        ),
        leaf("工单查重"),
      ),
      node("社群管理",
        node("群组工单",
          leaf("创建/编辑/分享/重置"),
        ),
        node("群组列表",
          leaf("群组数据统计"),
          leaf("标签管理"),
        ),
      ),
      node("内控管理",
        leaf("聊天记录"),
        leaf("敏感词监控"),
        leaf("收款管控"),
        leaf("敏感行为监控"),
        leaf("工作量统计"),
        leaf("合规统计"),
      ),
      node("素材管理（增强）",
        leaf("图片素材"),
        leaf("名片素材"),
      ),
      node("推广中心",
        leaf("我的账户"),
        leaf("推广有礼"),
      ),
      leaf("操作日志"),
    ),
  ),

  # ══════════════════════════════════════════
  node("SAAS总控端",
    node("一期",
      node("登录",
        leaf("账号密码"),
        leaf("双因素认证（2FA）"),
      ),
      node("概览大盘",
        leaf("在线租户数/活跃数"),
        leaf("今日/本月收入"),
        leaf("AI用量概览"),
        leaf("套餐到期预警"),
      ),
      node("租户管理",
        node("租户列表",
          leaf("新增/编辑/停用/启用/注销"),
          leaf("绑定套餐"),
          leaf("一键进入运营中台"),
        ),
        node("租户详情",
          leaf("基础信息"),
          leaf("套餐&到期时间"),
          leaf("附加包持有情况"),
          leaf("用量概览"),
        ),
      ),
      node("套餐管理",
        node("套餐列表",
          leaf("计费模式（买断/订阅）"),
          leaf("周期规格（30/90/180/365天）"),
          leaf("折扣配置（按周期）"),
          leaf("端口数量上限"),
          leaf("AI额度（买断=总量/订阅=每期重置）"),
          leaf("功能权限开关"),
          leaf("是否支持购买附加包"),
        ),
        leaf("套餐分组"),
      ),
      node("附加包管理（仅订阅租户）",
        node("AI Token 加油包",
          leaf("规格&定价"),
          leaf("有效期"),
          leaf("叠加规则"),
        ),
        node("端口扩展包",
          leaf("规格&定价"),
          leaf("随套餐周期到期"),
        ),
        leaf("附加包购买记录"),
      ),
      node("IP管理",
        node("IP套餐配置",
          leaf("规格（数量/类型/区域/有效期）"),
          leaf("定价"),
        ),
        leaf("租户IP购买记录"),
        leaf("IP分配状态（已分配/未分配/已到期）"),
        node("库存管理",
          leaf("可用IP数量"),
          leaf("低库存预警"),
        ),
      ),
      node("计费模块",
        node("账单管理",
          leaf("账单列表（自动/手动生成）"),
          leaf("账单状态（待支付/已支付/逾期）"),
          leaf("账单PDF下载"),
        ),
        node("余额管理",
          leaf("租户余额列表"),
          leaf("手动充值/扣减"),
          leaf("余额低预警配置"),
        ),
        node("欠费与停服",
          leaf("到期提醒通知"),
          leaf("宽限期配置"),
          leaf("自动停服规则"),
          leaf("续费恢复规则"),
        ),
        node("优惠券（基础）",
          leaf("新增/发放/停用"),
          leaf("使用记录"),
        ),
      ),
      node("支付模块",
        node("支付渠道配置",
          leaf("USDT"),
          leaf("PayPal"),
          leaf("支付宝"),
        ),
        node("支付流水",
          leaf("套餐购买/升级"),
          leaf("附加包购买"),
          leaf("IP购买"),
          leaf("AI消耗支出（回复/翻译/画像/总结）"),
          leaf("余额充值"),
          leaf("余额回收（系统/人工）"),
          leaf("分配支出"),
          leaf("异常流水标记"),
        ),
        leaf("退款处理（手动审核）"),
      ),
      node("AI用量统计",
        leaf("各租户Token消耗量"),
        leaf("按日/月趋势"),
        leaf("消耗排行"),
        leaf("剩余额度预警"),
      ),
      node("内容模板管理",
        node("意图库",
          leaf("新增/编辑/分组"),
          leaf("触发关键词"),
          leaf("意图分类（售前/售中/售后）"),
          leaf("适用平台"),
          leaf("下发配置（全部/套餐/租户）"),
        ),
        node("话术库",
          leaf("新增/编辑/分组"),
          leaf("适用意图绑定"),
          leaf("话术类型（欢迎语/销售/异议/促单/售后）"),
          leaf("支持变量（客户名/产品名）"),
          leaf("下发配置"),
        ),
        node("行业模板包",
          leaf("电商/教育/金融/自定义"),
          leaf("包含预置意图+话术"),
          leaf("一键下发给租户"),
        ),
        node("租户使用情况",
          leaf("已接收模板"),
          leaf("使用/未使用统计"),
          leaf("已自定义标记"),
        ),
      ),
      node("系统配置",
        leaf("平台名称/Logo"),
        node("VPN线路节点管理",
          leaf("节点列表（新增/编辑/启停）"),
          leaf("节点分组"),
          leaf("节点状态检测"),
        ),
        leaf("系统公告"),
      ),
      node("权限管理",
        leaf("总控账号管理"),
        leaf("角色配置（超管/运营/财务/技术支持）"),
        leaf("操作日志"),
      ),
      node("日志管理",
        leaf("登录日志"),
        leaf("操作日志"),
      ),
    ),
    node("二期",
      node("计费（增强）",
        leaf("自动续费（含失败重试）"),
        leaf("后付费/信用账期"),
        leaf("阶梯定价/批量折扣"),
        leaf("促销活动管理"),
        leaf("对账管理"),
      ),
      node("支付（增强）",
        leaf("更多渠道（微信/Stripe）"),
        leaf("自动退款"),
        leaf("回调日志&异常重试"),
      ),
      node("发票管理",
        leaf("开票申请审核"),
        leaf("电子发票配置"),
        leaf("纸质发票邮寄记录"),
      ),
      node("财务报表（完整）",
        leaf("收入分析（多维度）"),
        leaf("附加包/IP销售分析"),
        leaf("应收账款"),
        leaf("导出报表（Excel/CSV）"),
      ),
      node("AI资源管理（完整）",
        leaf("多模型接入与按套餐分配"),
        leaf("全局额度池管理"),
        leaf("调用监控&告警"),
        leaf("费用归因统计"),
      ),
      node("渠道商/代理管理",
        leaf("渠道商列表&分佣配置"),
        leaf("佣金结算"),
      ),
      node("运维监控",
        leaf("服务健康看板"),
        leaf("告警配置（企微/钉钉/邮件）"),
        leaf("数据库备份&恢复"),
      ),
      node("推广中心",
        leaf("对接运营中台推广数据"),
      ),
    ),
  ),
)

# ─── XML 生成 ──────────────────────────────────────────────

def build_xml_topic(parent_el, node_data):
    topic_el = ET.SubElement(parent_el, "topic")
    topic_el.set("id", mid())
    topic_el.set("timestamp", ts())
    title_el = ET.SubElement(topic_el, "title")
    title_el.text = node_data["title"]
    if node_data["children"]:
        children_el = ET.SubElement(topic_el, "children")
        topics_el = ET.SubElement(children_el, "topics")
        topics_el.set("type", "attached")
        for child in node_data["children"]:
            build_xml_topic(topics_el, child)
    return topic_el

def build_content_xml(tree_data):
    root = ET.Element("xmap-content")
    root.set("xmlns", "urn:xmind:xmap:xmlns:content:2.0")
    root.set("version", "2.0")
    root.set("timestamp", ts())

    sheet = ET.SubElement(root, "sheet")
    sheet.set("id", mid())
    sheet.set("timestamp", ts())

    build_xml_topic(sheet, tree_data)

    title_el = ET.SubElement(sheet, "title")
    title_el.text = "洽小秘产品规划"

    raw = ET.tostring(root, encoding="unicode")
    parsed = minidom.parseString(raw)
    return parsed.toprettyxml(indent="  ", encoding="UTF-8")

def build_manifest_xml():
    content = '''<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<manifest xmlns="urn:xmind:xmap:xmlns:manifest:1.0">
  <file-entry full-path="content.xml" media-type="text/xml"/>
  <file-entry full-path="meta.xml" media-type="text/xml"/>
</manifest>'''
    return content

def build_meta_xml():
    content = '''<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<meta xmlns="urn:xmind:xmap:xmlns:meta:2.0" version="2.0">
  <Creator>
    <Name>洽小秘产品规划</Name>
    <Version>1.0</Version>
  </Creator>
</meta>'''
    return content

# ─── 打包输出 ──────────────────────────────────────────────

output_path = "docs/洽小秘产品规划.xmind"

content_xml = build_content_xml(tree)
manifest_xml = build_manifest_xml()
meta_xml = build_meta_xml()

with zipfile.ZipFile(output_path, "w", zipfile.ZIP_DEFLATED) as zf:
    zf.writestr("content.xml", content_xml)
    zf.writestr("META-INF/manifest.xml", manifest_xml)
    zf.writestr("meta.xml", meta_xml)

print("OK: " + output_path)
